---
- name: restart bluetooth
  systemd:
    name: bluetooth
    state: restarted

- name: restart a2dp-agent
  systemd:
    name: a2dp-agent
    state: restarted

- name: restart pulseaudio
  systemd:
    name: pulseaudio
    state: restarted

- name: restart udev
  systemd:
    name: udev
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
